provider "aws" {
  region = "eu-west-1"
}

# Servers instances config

# variable "consul_server" {
#   default = ["consul1-dc1"]
# }

# source code for key_pair - https://cloudaffaire.com/faq/how-do-i-create-an-ssh-key-in-terraform/

## Define your key variable
variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

## Generate SSH key content using terraform
resource "tls_private_key" "dev_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

## Create a AWS key pair using the ssh key generated previously
## Stores the public key in aws and private key in the local system
resource "aws_key_pair" "generated_key" {
  key_name   = var.generated_key_name
  public_key = tls_private_key.dev_key.public_key_openssh

  provisioner "local-exec" { # Generate "terraform-key-pair.pem" in current directory
    command = <<-EOT
      echo '${tls_private_key.dev_key.private_key_pem}' > ./'${var.generated_key_name}'.pem
      chmod 400 ./'${var.generated_key_name}'.pem
    EOT
  }

}

#Server DC1

resource "aws_instance" "consul_server_dc1" {

  # for_each               = toset(var.consul_server)
  ami                    = "ami-08ca3fed11864d6bb"
  instance_type          = "t2.micro"
  vpc_security_group_ids = [aws_security_group.instance.id]
  key_name               = var.generated_key_name
  user_data              = data.template_file.server_data1.rendered
  iam_instance_profile   = aws_iam_instance_profile.instance_profile.name

  tags = {
    Name = "consul_server_dc1"
  }
}

data "template_file" "server_data1" {
  template = file("${path.module}/server-dc1-data.sh")
}

# Server DC2

resource "aws_instance" "consul_server_dc2" {

  # for_each               = toset(var.consul_server)
  ami                    = "ami-08ca3fed11864d6bb"
  instance_type          = "t2.micro"
  vpc_security_group_ids = [aws_security_group.instance.id]
  key_name               = var.generated_key_name
  user_data              = data.template_file.server_data2.rendered
  iam_instance_profile   = aws_iam_instance_profile.instance_profile.name

  tags = {
    Name = "consul_server_dc2"
  }
}

data "template_file" "server_data2" {
  template = file("${path.module}/server-dc2-data.sh")
}


# Clients instances config

# variable "consul_client" {
#   default = ["client1-dc1"]
# }

resource "aws_instance" "consul_client_dc1" {

  #for_each               = toset(var.consul_client)
  ami                    = "ami-08ca3fed11864d6bb"
  instance_type          = "t2.micro"
  vpc_security_group_ids = [aws_security_group.instance.id]
  key_name               = var.generated_key_name
  user_data              = data.template_file.client_data1.rendered
  iam_instance_profile   = aws_iam_instance_profile.instance_profile.name


  tags = {
    Name = "consul_client_dc1"
  }
}

data "template_file" "client_data1" {
  template = file("${path.module}/client-dc1-data.sh")
}

# Client DC2

resource "aws_instance" "consul_client_dc2" {

  #for_each               = toset(var.consul_client)
  ami                    = "ami-08ca3fed11864d6bb"
  instance_type          = "t2.micro"
  vpc_security_group_ids = [aws_security_group.instance.id]
  key_name               = var.generated_key_name
  user_data              = data.template_file.client_data2.rendered
  iam_instance_profile   = aws_iam_instance_profile.instance_profile.name


  tags = {
    Name = "consul_client_dc2"
  }
}

data "template_file" "client_data2" {
  template = file("${path.module}/client-dc2-data.sh")
}

resource "aws_security_group" "instance" {
  name = "consul-test-instance"
  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

